---
command: vigilia --config-filename ./vigilia2.config
command_tests:
  - description: Do we get a correct error message when the custom configuration file has syntax errors?
    read: |
      /usr/local/bin/vigilia: Error reading './vigilia2.config' (syntax error at ./vigilia2.config line 32, near "+ ;"
      ) at /usr/local/bin/vigilia line 2232.
    white_space: convert seen 0a to 0d 0a newlines
description: Do we get a correct error message when the custom configuration file has syntax errors?
