#!/usr/bin/perl -w

use strict;

use warnings;


package main;

our $option_verbose;

our $global_technical_project_configuration;


package Command;


my $workflow_project_directory = "$ENV{HOME}/projects/workflow-automation-engine/source/snapshots/master";


sub features_build
{
}


sub features_build_help
{
    my $command = shift;

    return "$command: Build the features of the workflow engine.

no arguments.

Note: This command converts the regression test specifications first to latex, then to pdf.
";
}


sub features_build_manual
{
}


sub features_build_manual_show
{
    features_build_manual();
}


sub features_build_show
{
    features_build();
}


sub features_build_show_help
{
    my $command = shift;

    return "$command: Build and show the features of the workflow engine.

no arguments.

Note: This command converts the regression test specifications first to latex, then to pdf.
";
}


# return success

1;


