FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Update system and install the required tools
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        apt-utils \
        automake \
        make \
        git \
        gcc \
        screen \
        sudo \
        unzip \
        vim \
        python3-dev python3-setuptools python3-wheel \
        libclone-perl \
        libexpect-perl \
        libfile-chdir-perl \
        libfile-find-rule-perl \
        libinline-perl \
        libipc-system-simple-perl \
        libjson-perl \
        libnet-ip-perl \
        libtoml-perl \
        libyaml-perl \
        grc \
        openssh-server \
        sshpass \
        tmux \
        libfaketime \
    && rm -rf /var/lib/apt/lists/*

# Set up locale
#         locales \
# RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
#     locale-gen
# ENV LANG=en_US.UTF-8 \
#     LANGUAGE=en_US:en \
#     LC_ALL=en_US.UTF-8

# Create a first test user
ARG GROUP_ID=10000
ARG USER_NAME=neurospaces
ARG USER_ID=10000

RUN groupadd --gid ${GROUP_ID} ${USER_NAME} && \
    useradd -m -u ${USER_ID} -g ${GROUP_ID} -s /bin/bash ${USER_NAME} && \
    echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USER_NAME}

# Create a second test user
ARG GROUP_ID_2=10001
ARG USER_NAME_2=neurospaces2
ARG USER_ID_2=10001

RUN groupadd --gid ${GROUP_ID_2} ${USER_NAME_2} && \
    useradd -m -u ${USER_ID_2} -g ${GROUP_ID_2} -s /bin/bash ${USER_NAME_2}

# Set working directory
USER ${USER_NAME}
WORKDIR /home/${USER_NAME}

ARG WORKING_DIRECTORY=/home/${USER_NAME}
RUN mkdir -p ${WORKING_DIRECTORY}/projects/workflow-automation-engine/source/snapshots/master

# note that a COPY command disables the Docker caches from here on

COPY --chown=${USER_NAME} . /home/${USER_NAME}/projects/workflow-automation-engine/source/snapshots/master

# install the workflow engine

WORKDIR /home/${USER_NAME}/projects/workflow-automation-engine/source/snapshots/master

RUN rm ./neurospaces_cpan_modules
RUN ./autogen.sh
RUN ./configure
RUN make
RUN sudo make install

WORKDIR /home/${USER_NAME}

