FROM fedora:40

# Avoid interactive prompts during package installs
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV TZ=UTC

# Update and install required tools
RUN dnf -y update && \
    dnf -y install \
        automake \
        make \
        git \
        gcc \
        screen \
        sudo \
        unzip \
        vim \
        python3-devel python3-setuptools python3-wheel \
        perl-Clone \
        perl-Expect \
        perl-File-chdir \
        perl-File-Find-Rule \
        perl-Inline \
        perl-IPC-System-Simple \
        perl-JSON \
        perl-Net-IP \
        perl-App-cpanminus \
        perl-YAML \
        grc \
        openssh-server \
        sshpass \
        tmux \
        libfaketime \
        glibc-langpack-en \
        && cpanm --notest TOML \
        && dnf clean all && rm -rf /var/cache/dnf

# Create first test user
ARG GROUP_ID=10000
ARG USER_NAME=neurospaces
ARG USER_ID=10000

RUN groupadd -g ${GROUP_ID} ${USER_NAME} && \
    useradd -m -u ${USER_ID} -g ${GROUP_ID} -s /bin/bash ${USER_NAME} && \
    echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USER_NAME}

# Create second test user
ARG GROUP_ID_2=10001
ARG USER_NAME_2=neurospaces2
ARG USER_ID_2=10001

RUN groupadd -g ${GROUP_ID_2} ${USER_NAME_2} && \
    useradd -m -u ${USER_ID_2} -g ${GROUP_ID_2} -s /bin/bash ${USER_NAME_2}

# Switch to working user
USER ${USER_NAME}
WORKDIR /home/${USER_NAME}

ARG WORKING_DIRECTORY=/home/${USER_NAME}
RUN mkdir -p ${WORKING_DIRECTORY}/projects/workflow-automation-engine/source/snapshots/master

# Copy project sources
COPY --chown=${USER_NAME} . /home/${USER_NAME}/projects/workflow-automation-engine/source/snapshots/master

# Build and install the workflow engine
WORKDIR /home/${USER_NAME}/projects/workflow-automation-engine/source/snapshots/master

RUN rm -f ./neurospaces_cpan_modules
RUN ./autogen.sh
RUN ./configure
RUN make
RUN sudo make install

WORKDIR /home/${USER_NAME}
