#!/usr/bin/perl -w

use strict;

use warnings;


package main;

our $option_verbose;

our $global_technical_project_configuration;


package Command;


our $target_servers = $::global_technical_project_configuration->{target_servers};

# return success

1;


