#!/usr/bin/perl -w

use strict;

use warnings;


package main;

our $option_verbose;

our $global_technical_project_configuration;

our $global_field_project_configuration;

package Command;


my $workflow_project_directory = "$global_field_project_configuration->{sources_configuration_directory}/..";

sub _documentation_vigilia_build
{
    my $tags = shift;

    my $command_line_tags = $tags ? "--tags " . (join ' ', @$tags) : '';

    my $commands
	= [
	   "bin/vigilia --output-pdf --output-figures --verbose --output-content-line-limit 3000 $command_line_tags",
	  ];

    execute_shell_command_array($commands);
}


sub _documentation_workflow_build
{
    my $tags = shift;

    my $command_line_tags = $tags ? "--tags " . (join ' ', @$tags) : '';

    my $commands
	= [
	   "bin/workflow builtin manual builtin -- --no-view",
	  ];

    execute_shell_command_array($commands);
}


sub _documentation_vigilia_show
{
    my $commands
	= [
	   "setsid okular report_workflow-automation-engine/test_report_workflow-automation-engine_command_definition-command_test-meta-module.pdf >/dev/null 2>&1 < /dev/null &"

# 	   "nohup okular report_workflow-automation-engine/test_report_workflow-automation-engine_command_definition-command_test-meta-module.pdf",
	  ];

    execute_shell_command_array($commands);
}


sub _documentation_workflow_show
{
    my $commands
	= [
	   "setsid okular workflow-engine-manual-builtin.pdf >/dev/null 2>&1 < /dev/null &"
	  ];

    execute_shell_command_array($commands);
}


sub documentation_build
{
    my $commands
	= [
	   "cd $workflow_project_directory",
	  ];

    execute_shell_command_array($commands);

    _documentation_vigilia_build();

    _documentation_workflow_build();
}


sub documentation_build_help
{
    my $command = shift;

    return "$command: Build the documentation of the workflow engine.

no arguments.

Note: This command converts the regression test specifications first to latex, then to pdf.
";
}


sub documentation_help
{
    my $command = shift;

    return "$command: Build the documentation of the workflow engine and vigilia.
";
}


sub documentation_build_manual
{
    my $commands
	= [
	   "cd $workflow_project_directory",
	  ];

    execute_shell_command_array($commands);

    _documentation_vigilia_build( [ 'manual' ] );

    _documentation_workflow_build( [ 'manual' ] );
}


sub documentation_build_manual_show
{
    documentation_build_manual();

    _documentation_vigilia_show();

    _documentation_workflow_show();
}


sub documentation_build_show
{
    documentation_build();

    _documentation_vigilia_show();

    _documentation_workflow_show();
}


sub documentation_build_show_help
{
    my $command = shift;

    return "$command: Build and show the documentation of the workflow engine.

no arguments.

Note: This command converts the regression test specifications first to latex, then to pdf.
";
}


sub markdown_view
{
    my $arguments = shift || [];

    my $filename = $arguments->[0] || "Some-dummy-file";

    my $commands
	= [
	   "pandoc $filename --output /tmp/document.pdf && okular /tmp/document.pdf",
	  ];

    execute_shell_command_array($commands);
}


sub _builtin_completor_filename_extension_completions
{
    my $current_word = shift // '';

    my $extensions = shift;;

    # Completion is deliberately limited to the current working directory
    # and its descendants.
    return {}
        if $current_word =~ m{\A/};

    my @path_components = split m{/+}, $current_word, -1;

    return {}
        if grep { $_ eq '..' } @path_components;

    # Examples:
    #
    #   current word       directory prefix    entry prefix
    #   ------------       ----------------    ------------
    #   RE                 ""                  RE
    #   documentation/     documentation/      ""
    #   documentation/RE   documentation/      RE

    my ($directory_prefix, $entry_prefix)
        = $current_word =~ m{\A(.*/)([^/]*)\z}
        ? ($1, $2)
        : ('', $current_word);

    my $directory
        = length $directory_prefix
        ? $directory_prefix
        : '.';

    opendir(my $directory_handle, $directory)
        or return {};

    my $completions = {};

    foreach my $entry (sort readdir $directory_handle)
    {
        next
            if $entry eq '.'
            or $entry eq '..';

        # Behave like ordinary Bash filename completion: hidden entries
        # are shown only after the user has typed a leading dot.
        next
            if $entry =~ /^\./
            and $entry_prefix !~ /^\./;

        next
            if index($entry, $entry_prefix) != 0;

        my $candidate = $directory_prefix . $entry;

        if (-d $candidate)
        {
            # The slash indicates that completion can continue inside
            # this directory.
            $candidate .= '/';
        }
	elsif (-f $candidate and $entry =~ /$extensions\z/i)
        {
            # This is an eligible Markdown file.
        }
        else
        {
            next;
        }

        # The generated Bash completion code passes the candidates through
        # compgen -W, matching the convention already used by the PDF
        # filename completor in workflow.
        $candidate =~ s/(\s)/\\$1/g;

        $completions->{$candidate} = '';
    }

    closedir $directory_handle;

    return $completions;
}


sub _builtin_markdown_file_completor
{
    my $operation_name = shift // '';

    my $complete_arguments_array = shift;

    my $analysis = shift;

    $complete_arguments_array = []
        if ref $complete_arguments_array ne 'ARRAY';

    $analysis = {}
        if ref $analysis ne 'HASH';

    my $operation_path
        = [
           grep { length $_ }
           split /\s+/, $operation_name,
          ];

    my $bash_variables
        = ref $analysis->{bash} eq 'HASH'
        ? $analysis->{bash}
        : {};

    my $current_word_index;

    my $current_word_is_present;

    # COMP_CWORD counts words including the executable, whereas
    # complete_arguments_array no longer contains that executable.
    if (defined $bash_variables->{comp_cword}
        and $bash_variables->{comp_cword} > 0)
    {
        $current_word_index = $bash_variables->{comp_cword} - 1;

        $current_word_is_present
            = exists $complete_arguments_array->[$current_word_index];
    }
    elsif (defined $analysis->{string_before_point})
    {
        $current_word_is_present
            = $analysis->{string_before_point} !~ /\s\z/;

        $current_word_index = $#$complete_arguments_array
            if $current_word_is_present
            and @$complete_arguments_array;
    }
    else
    {
        # Compatibility fallback for callers that provide neither the Bash
        # state nor string_before_point. Anything following the operation
        # path is treated as the current partial argument.
        $current_word_is_present
            = scalar(@$complete_arguments_array)
            > scalar(@$operation_path);

        $current_word_index = $#$complete_arguments_array
            if $current_word_is_present;
    }

    my $current_word
        = $current_word_is_present
        ? ($complete_arguments_array->[$current_word_index] // '')
        : '';

    # _builtin_completor_expander() currently assumes this field is always
    # defined. Supply an equivalent sentinel when the caller omitted it:
    # non-whitespace means a partial word; whitespace means a new word.
    my $expander_analysis = { %$analysis };

    if (not defined $expander_analysis->{string_before_point})
    {
        $expander_analysis->{string_before_point}
            = $current_word_is_present ? 'x' : ' ';
    }

    my $extensions = ".md";

    return _builtin_completor_expander
        (
         analysis => $expander_analysis,
         complete_arguments_array => $complete_arguments_array,
         operation_path => $operation_path,
         positional_arguments => [
                                  {
                                   completions
                                       => _builtin_completor_filename_extension_completions
                                          (
                                           $current_word,
					   $extensions,
                                          ),
                                  },
                                 ],
        );
}


sub markdown_view_completions
{
    return _builtin_markdown_file_completor(@_);
}


sub markdown_view_help
{
    my $command = shift;

    return "$command: A pandoc based markdow viewer that comes with no complicated installation instructions.

This depends on the availability of 'pandoc' and 'Latex' which are available for all major Linux distributions.

Arguments:
~~~~~~~~~~

ARGV[0]: A markdown file.

";
}


# return success

1;


