#!/usr/bin/perl -w

use strict;

use warnings;


package main;

our $option_verbose;

our $global_technical_project_configuration;


package Command;


my $container_enter_command = "docker exec -it workflow_automation_test_container bash";

my $workflow_project_directory = "$ENV{HOME}/projects/workflow-automation-engine/source/snapshots/master";


sub test_enter
{
    my $commands
	= [
	   "cd $workflow_project_directory",
	   "echo To enter the test container, use a command similar to\\'$container_enter_command\\'",
# 	   "setsid okular /tmp/test_report_workflow-automation-engine/test_report_workflow-automation-engine_command_definition-command_test-meta-module.pdf >/dev/null 2>&1 < /dev/null &"

# 	   "nohup okular /tmp/test_report_workflow-automation-engine/test_report_workflow-automation-engine_command_definition-command_test-meta-module.pdf",

	   "echo The known test containers are:",
	   "bin/vigilia --show-images",
	  ];

    execute_shell_command_array($commands);
}


sub _test_read_known_containers
{
    my $selected_images_yaml = `bin/vigilia --show-images`;

    #t $selected_images_yaml starts with three asterisks, no idea why ...

    $selected_images_yaml =~ s(\*)()g;

    $selected_images_yaml =~ s( Info: See.*)()gs;

    return $selected_images_yaml;
}


sub test_enter_completions
{
    my $selected_images_yaml = _test_read_known_containers();

    use YAML;

    my $selected_images = Load($selected_images_yaml);

    my $images = $selected_images->{selected};

    my $container_names
	= [
	   sort
	   map
	   {
	       $images->{$_}->{name_container};
	   }
	   keys %$images,
	  ];

    my $completions
	= {
	   map
	   {
	       $_ => '',
	   }
	   @$container_names,
	  };

    return $completions;
}


sub test_enter_help
{
    my $command = shift;

    my $selected_images_yaml = _test_read_known_containers();

    return "$command: Display the command to enter a test container and give a hint regarding the known containers.

no arguments.
";

# Known containers are:

# $selected_images_yaml
# ";
}

package main;

our $global_execute_scheduled_commands;


package Command;


sub test_perl_2_yaml
{
    my $arguments = shift;

    my $old_test_pathname = $arguments->[0];

    my $format = $arguments->[1] || 'json';

    my $replace = $arguments->[2] || '';

    # make sure the --interactions family of options works

    if (not $::global_execute_scheduled_commands)
    {
	if (! $old_test_pathname)
	{
	    $old_test_pathname = "some-path-name-that-allows-sensible-output-in-the-documentation";
	}
    }

    if (! $old_test_pathname)
    {
	die "$0: *** Error: expected a single argument for the test_pathname.";
    }

    if ($format ne 'yaml'
	and $format ne 'json')
    {
	die "$0: *** Error: format should be 'json' or 'yaml' (now it is '$format'.";
    }

    my $new_test_pathname = $old_test_pathname;

    $new_test_pathname =~ s(.t$)();

    my $conversion_commands
	= [
	   "vigilia --regex $old_test_pathname --dump-file-structured-$format",
	   "echo The result of the conversion is found as",
	   "echo",
	   "echo     /tmp/tests/specifications/$new_test_pathname/summary.yml",
	   "echo     /tmp/tests/specifications/$new_test_pathname/command_definitions/*",
	   "echo",
	   (not $replace) ? ("echo Use a second argument for the command you just used, to automatically replace the previous test with its converted version.") : (),
	  ];

    execute_shell_command_array
	(
	 $conversion_commands,
	 {
	  allow_fail => 'if some of the tests fail, vigilia returns a failure code',
	  quiet => 'for better visual output',
	 },
	);

    if ($replace)
    {
	my $option_config_filename = './tests.config';
	my $test_config = do $option_config_filename;

	if (not exists $test_config->{tests_directory})
	{
	    $test_config->{tests_directory} = "./tests/specifications";
	}

	my $tests_directory = $test_config->{tests_directory};

	my $replace_commands
	    = [
	       "rm -fr $tests_directory/$old_test_pathname*",
	       "mv /tmp/$tests_directory/$new_test_pathname $tests_directory/$new_test_pathname",
	      ];

	execute_shell_command_array($replace_commands);
    }

}


sub test_perl_2_yaml_help
{
    my $command = shift;

    return "$command: convert a test module in perl to file-structured json or yaml in /tmp.

For a format of 'json' this command is equivalent to:

\$ vigilia --regex <test_pathname> --dump-file-structured-json

For a format of 'yaml' this command is equivalent to:

\$ vigilia --regex <test_pathname> --dump-file-structured-yaml

with some extras.

arguments:

    ARGV[0]: The existing test pathname, note that this is processed as a regex.
    ARGV[1]: Either 'json' or 'yaml', the default is 'json'.
    ARGV[2]: 'replace' or any string to replace the existing test with its yaml version.
";
}


# return success

1;


