#!/usr/bin/perl -w

use strict;

use warnings;


package main;

our $option_verbose;

our $global_technical_project_configuration;


package Command;


our $target_servers = $::global_technical_project_configuration->{target_servers};


sub test_enter
{
    my $commands
	= [
# 	   "setsid okular /tmp/test_report_workflow-automation-engine/test_report_workflow-automation-engine_command_definition-command_test-meta-module.pdf >/dev/null 2>&1 < /dev/null &"

# 	   "nohup okular /tmp/test_report_workflow-automation-engine/test_report_workflow-automation-engine_command_definition-command_test-meta-module.pdf",
	  ];

    execute_shell_command_array($commands);
}


sub test_enter_help
{
    my $command = shift;

    return "$command: Display the command to enter the test container.

no arguments.
";
}


# return success

1;


