#!/usr/bin/perl -w
#!/usr/bin/perl -w -d:ptkdb

use strict;

my $module_filenames = [ sort @ARGV, ];

use Data::Dumper;

print "Installing CPAN modules\n";

print Dumper($module_filenames);

foreach my $module_filename (@$module_filenames)
{
    $module_filename =~ /^...(.*)\.tar\.gz$/i;

    my $module_name = $1;

    if ($module_name =~ /inline-python/i)
    {
	next;
    }

    $module_name =~ /([^0-9\.]+)-([0-9\.]+)/;

    my $module_perl = $1;

    my $module_version_to_install = $2;

    $module_perl =~ s/-/::/g;

    print "checking for perl -e 'use $module_perl $module_version_to_install'\n";
    system "perl -e 'use $module_perl $module_version_to_install'";

    my $installed = not $?;

    if ($installed)
    {
	print "Not installing $module_name ($module_filename), it looks like it is already installed\n";

	next;
    }

    print "Installing $module_name ($module_filename)\n";

    print `pwd`;

    system "tar xfz $module_filename --no-same-owner --no-same-permissions";

    chdir $module_name;

    print `pwd`;

    if ($module_name =~ /inline-python/i)
    {
	system "echo '' | perl Makefile.PL";
    }
    elsif ($module_name =~ /inline/i)
    {
	system "echo y | perl Makefile.PL";
    }
    else
    {
	system "perl Makefile.PL";
    }

    system "make";

    system "make test";

    system "sudo make install";

    chdir "..";

    system "rm -fr $module_name";

}


