#!/usr/bin/perl -w
#!/usr/bin/perl -w -d:ptkdb

use strict;

my $module_filenames = [ sort @ARGV, ];

use Data::Dumper;

print "Installing CPAN modules\n";

print Dumper($module_filenames);

# loop over all required modules

foreach my $module_filename (@$module_filenames)
{
    # skip inline python

    #t why?

    $module_filename =~ /^...(.*)\.tar\.gz$/i;

    my $module_name = $1;

    if ($module_name =~ /inline-python/i)
    {
	next;
    }

    # is this module already installed?

    $module_name =~ /([^0-9\.]+)-([0-9\.]+)/;

    my $module_perl = $1;

    my $module_version_to_install = $2;

    $module_perl =~ s/-/::/g;

    print "checking for perl -e 'use $module_perl $module_version_to_install'\n";
    system "perl -e 'use $module_perl $module_version_to_install'";

    my $installed = not $?;

    if ($installed)
    {
	# module is already installed, skip it

	print "Not installing $module_name ($module_filename), it looks like it is already installed\n";

	next;
    }

    print "Installing $module_name ($module_filename)\n";

    print `pwd`;

    # unpack the module

    system "tar xfz $module_filename --no-same-owner --no-same-permissions";

    chdir $module_name;

    print `pwd`;

    # run the perl makefile

    # inline python ...

    if ($module_name =~ /inline-python/i)
    {
	# ... uses an interactive perl makefile

	system "echo '' | perl Makefile.PL";
    }

    # ... other inline modules ...

    elsif ($module_name =~ /inline/i)
    {
	# ... have perl makefiles that ask questions that should be answered with 'y'es.

	system "echo y | perl Makefile.PL";
    }

    # ... other modules ...

    else
    {
	# ... don't require special handling

	system "perl Makefile.PL";
    }

    # build and install

    system "make";

    system "make test";

    system "sudo make install";

    chdir "..";

    system "rm -fr $module_name";

}


